<?php
namespace common\models;
class Test extends Base
{
    static function tableName()
    {
        return "{{%users}}";
    }

    public function getList()
    {
        return 50;
    }
    public function fetchListAll($where = array(), $limit = null, $offset = null, $order = null)
    {
        return parent::fetchListAll($where, $limit, $offset, $order); // TODO: Change the autogenerated stub

    }

    function getimage($url,$filename='',$type=1){

    }

}
