<?php
/**
 * Created by PhpStorm.
 * User: xia
 * Date: 2018/8/31
 * Time: 8:29
 */

namespace frontend\models;

use common\models\Base;
use common\models\San;

class FrSan extends San
{

    public function fetchListAll($where = array(), $limit = null, $offset = null, $order = null)
    {
        return parent::fetchListAll($where, $limit, $offset, $order); // TODO: Change the autogenerated stub
    }

}